### ISSUE TITLE
Issue #2

### ISSUE THREAD

**Issue by Lakshsharma31** [AliAryanTech/Neko-Chan#2]
Hello bro please make some 18+ or sex rated stickers telegram urls in your repo and upload so it will be a pleasure for us  ❤🦄

**Comment by AliAryanTech** [comment]
Actually, Telegram don't have much video Po** stickers... But still I found this - [Pack](https://t.me/addstickers/FapPornSexVulgarKissLoveNsfwXXX) 

I don't know it will be fine or not..

Anyways, I added some more in that package... Next Time
Provide the url of that stickers pack which you want.. 👀

**Comment by AliAryanTech** [comment]
> Hello bro please make some 18+ or sex rated stickers telegram urls in your repo and upload so it will be a pleasure for us ❤🦄

Done - [Here](https://githubuser.com/AliAryanTech/Neko-Chan/main/Webps/Porno.json)
